# Generated by Django 4.0.2 on 2022-02-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(default='', max_length=15)),
                ('title', models.CharField(default='', max_length=2)),
            ],
        ),
    ]
