# Generated by Django 4.0.2 on 2022-03-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessStats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.CharField(default='', max_length=15, primary_key=True, serialize=False),
        ),
    ]