# Generated by Django 4.0.2 on 2022-03-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessStats', '0002_test_remove_player_id_alter_player_player_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='id',
        ),
        migrations.RemoveField(
            model_name='test',
            name='shravan',
        ),
        migrations.AddField(
            model_name='test',
            name='Shravan',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
