# Generated by Django 4.0.2 on 2022-04-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessStats', '0003_remove_test_id_remove_test_shravan_test_shravan'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('salt', models.BigIntegerField()),
                ('passwordHash', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='title',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
