# Generated by Django 4.0.2 on 2022-04-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessStats', '0003_remove_test_id_remove_test_shravan_test_shravan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('date_utc', models.CharField(max_length=45)),
                ('time_utc', models.CharField(max_length=45)),
                ('weekday', models.CharField(max_length=45)),
                ('date_id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.IntegerField(default=0, max_length=11)),
                ('name', models.CharField(default='', max_length=45, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.IntegerField(default=0, max_length=11, primary_key=True, serialize=False)),
                ('date_id', models.IntegerField(max_length=11)),
                ('turns', models.CharField(default='', max_length=45)),
                ('termination', models.CharField(default='', max_length=45)),
                ('winner', models.CharField(default='', max_length=45)),
                ('black_id', models.CharField(default='', max_length=45)),
                ('white_id', models.CharField(default='', max_length=45)),
                ('opening_id', models.IntegerField(max_length=11)),
                ('event_id', models.IntegerField(max_length=11)),
                ('time_control', models.CharField(default='', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('opening_id', models.IntegerField(default=0, max_length=11)),
                ('name', models.CharField(default='', max_length=45, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='elo',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='player',
            name='games_played',
            field=models.IntegerField(default=0, max_length=11),
        ),
        migrations.AddField(
            model_name='player',
            name='games_won',
            field=models.IntegerField(default=0, max_length=11),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.CharField(default='', max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='title',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
    ]
